# Generated by Django 4.2.1 on 2023-06-02 07:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=tinymce.models.HTMLField(blank=True, max_length=100),
        ),
    ]
